### ISSUE TITLE
理论基础-CSS3动画

### ISSUE THREAD

**Issue by fly0o0** [fly0o0/blog#37]
## 1.transform变形

transform属性可以对元素进行一些转换，转换前后不会影响相邻元素的位置。

常见的2D转换包括平移(translate)、缩放(scale)、旋转(rotate)和偏移(skew)：

``` css
    transform: translate(100px, 200px);
    transform: scale(2, 4);
    transform: rotate(45deg);
    transform: skew(20deg, 30deg);
```

旋转和缩放的注册点默认为元素中心，可以通过transform-origin属性修改:

``` css
transform-origin:100% 100%;
```

可以通过rotateX和rotateY进行3D旋转：

``` css
    transform: rotateX(45deg);
    transform: rotateY(45deg);
```
## 2.transition过渡

过渡(transition)可以为元素增加简单的补间动画。若要改变单个属性数值：

```
div { width:100px; transition:width 1s linear 0.4s; }
div:hover {width:200px;}
```

transition的数值分别是：过渡属性名，过渡时间，过渡缓动函数，过渡延时。

过渡多个属性之间用逗号分隔：

``` css
div { transition:width 2s, height 1s; }
```
## 3.animation动画

对于更复杂的动画，需要借助@keyframes和animation属性。@keyframes用来定义动画，animation将定义好的动画绑定到特定元素，并定义动画时长、重复次数等相关属性。

``` css
    @keyframes myfirst {
        0% { background:red;}
        25% { background:orange;}
        50% { background:yellow;}
        100% { background:green;}
    }
```

```
div { animation: myfirst 2s; }
```
